# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official
android.disallowKotlinSourceSets=false

# 使用 JDK 17 绕过 toolchain 自动下载
org.gradle.java.installations.fromEnv=JAVA_HOME
org.gradle.java.installations.paths=C\:\\Program Files\\Amazon Corretto\\jdk17.0.19_10
